//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 07:36:19 PM EAT 
//


package org.kephis.cms.xmlschema.SPSCertificate_8p0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ID"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}Name"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}RoleCode"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}SpecifiedSPSAddress"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "name",
    "roleCode",
    "specifiedSPSAddress"
})
@XmlRootElement(name = "ConsignorSPSParty")
public class ConsignorSPSParty {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "RoleCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String roleCode;
    @XmlElement(name = "SpecifiedSPSAddress", required = true)
    protected SpecifiedSPSAddress specifiedSPSAddress;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the roleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * Sets the value of the roleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleCode(String value) {
        this.roleCode = value;
    }

    /**
     * Gets the value of the specifiedSPSAddress property.
     * 
     * @return
     *     possible object is
     *     {@link SpecifiedSPSAddress }
     *     
     */
    public SpecifiedSPSAddress getSpecifiedSPSAddress() {
        return specifiedSPSAddress;
    }

    /**
     * Sets the value of the specifiedSPSAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecifiedSPSAddress }
     *     
     */
    public void setSpecifiedSPSAddress(SpecifiedSPSAddress value) {
        this.specifiedSPSAddress = value;
    }

}
