//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 07:36:19 PM EAT 
//


package org.kephis.cms.xmlschema.SPSCertificate_8p0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}SequenceNumeric"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}Description"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}CommonName"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ScientificName"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}GrossWeightMeasure"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}NetWeightMeasure"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}AdditionalInformationSPSNote"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ApplicableSPSClassification" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}PhysicalSPSPackage"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}OriginSPSCountry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sequenceNumeric",
    "description",
    "commonName",
    "scientificName",
    "grossWeightMeasure",
    "netWeightMeasure",
    "additionalInformationSPSNote",
    "applicableSPSClassification",
    "physicalSPSPackage",
    "originSPSCountry"
})
@XmlRootElement(name = "IncludedSPSTradeLineItem")
public class IncludedSPSTradeLineItem {

    @XmlElement(name = "SequenceNumeric", required = true)
    protected BigInteger sequenceNumeric;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "CommonName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String commonName;
    @XmlElement(name = "ScientificName", required = true)
    protected String scientificName;
    @XmlElement(name = "GrossWeightMeasure")
    protected GrossWeightMeasure grossWeightMeasure;
    @XmlElement(name = "NetWeightMeasure")
    protected NetWeightMeasure netWeightMeasure;
    @XmlElement(name = "AdditionalInformationSPSNote", required = true)
    protected AdditionalInformationSPSNote additionalInformationSPSNote;
    @XmlElement(name = "ApplicableSPSClassification", required = true)
    protected List<ApplicableSPSClassification> applicableSPSClassification;
    @XmlElement(name = "PhysicalSPSPackage", required = true)
    protected PhysicalSPSPackage physicalSPSPackage;
    @XmlElement(name = "OriginSPSCountry", required = true)
    protected OriginSPSCountry originSPSCountry;

    /**
     * Gets the value of the sequenceNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNumeric() {
        return sequenceNumeric;
    }

    /**
     * Sets the value of the sequenceNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNumeric(BigInteger value) {
        this.sequenceNumeric = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the commonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * Sets the value of the commonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonName(String value) {
        this.commonName = value;
    }

    /**
     * Gets the value of the scientificName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScientificName() {
        return scientificName;
    }

    /**
     * Sets the value of the scientificName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScientificName(String value) {
        this.scientificName = value;
    }

    /**
     * Gets the value of the grossWeightMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link GrossWeightMeasure }
     *     
     */
    public GrossWeightMeasure getGrossWeightMeasure() {
        return grossWeightMeasure;
    }

    /**
     * Sets the value of the grossWeightMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrossWeightMeasure }
     *     
     */
    public void setGrossWeightMeasure(GrossWeightMeasure value) {
        this.grossWeightMeasure = value;
    }
    /**
     * Gets the value of the grossWeightMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link NetWeightMeasure }
     *     
     */
    public NetWeightMeasure getNetWeightMeasure() {
        return netWeightMeasure;
    }

    /**
     * Sets the value of the grossWeightMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetWeightMeasure }
     *     
     */
    public void setNetWeightMeasure(NetWeightMeasure value) {
        this.netWeightMeasure = value;
    }
    /**
     * Gets the value of the additionalInformationSPSNote property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInformationSPSNote }
     *     
     */
    public AdditionalInformationSPSNote getAdditionalInformationSPSNote() {
        return additionalInformationSPSNote;
    }

    /**
     * Sets the value of the additionalInformationSPSNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInformationSPSNote }
     *     
     */
    public void setAdditionalInformationSPSNote(AdditionalInformationSPSNote value) {
        this.additionalInformationSPSNote = value;
    }

    /**
     * Gets the value of the applicableSPSClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicableSPSClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicableSPSClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicableSPSClassification }
     * 
     * 
     */
    public List<ApplicableSPSClassification> getApplicableSPSClassification() {
        if (applicableSPSClassification == null) {
            applicableSPSClassification = new ArrayList<ApplicableSPSClassification>();
        }
        return this.applicableSPSClassification;
    }

    /**
     * Gets the value of the physicalSPSPackage property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalSPSPackage }
     *     
     */
    public PhysicalSPSPackage getPhysicalSPSPackage() {
        return physicalSPSPackage;
    }

    /**
     * Sets the value of the physicalSPSPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalSPSPackage }
     *     
     */
    public void setPhysicalSPSPackage(PhysicalSPSPackage value) {
        this.physicalSPSPackage = value;
    }

    /**
     * Gets the value of the originSPSCountry property.
     * 
     * @return
     *     possible object is
     *     {@link OriginSPSCountry }
     *     
     */
    public OriginSPSCountry getOriginSPSCountry() {
        return originSPSCountry;
    }

    /**
     * Sets the value of the originSPSCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginSPSCountry }
     *     
     */
    public void setOriginSPSCountry(OriginSPSCountry value) {
        this.originSPSCountry = value;
    }

}
