//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 07:36:19 PM EAT 
//


package org.kephis.cms.xmlschema.SPSCertificate_8p0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ModeCode"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}UsedSPSTransportMeans"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modeCode",
    "usedSPSTransportMeans"
})
@XmlRootElement(name = "MainCarriageSPSTransportMovement")
public class MainCarriageSPSTransportMovement {

    @XmlElement(name = "ModeCode", required = true)
    protected BigInteger modeCode;
    @XmlElement(name = "UsedSPSTransportMeans", required = true)
    protected UsedSPSTransportMeans usedSPSTransportMeans;

    /**
     * Gets the value of the modeCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getModeCode() {
        return modeCode;
    }

    /**
     * Sets the value of the modeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setModeCode(BigInteger value) {
        this.modeCode = value;
    }

    /**
     * Gets the value of the usedSPSTransportMeans property.
     * 
     * @return
     *     possible object is
     *     {@link UsedSPSTransportMeans }
     *     
     */
    public UsedSPSTransportMeans getUsedSPSTransportMeans() {
        return usedSPSTransportMeans;
    }

    /**
     * Sets the value of the usedSPSTransportMeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsedSPSTransportMeans }
     *     
     */
    public void setUsedSPSTransportMeans(UsedSPSTransportMeans value) {
        this.usedSPSTransportMeans = value;
    }

}
