//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 07:36:19 PM EAT 
//
 
@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12", 
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        
        xmlns = {
        @javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12", prefix = "rsm"),
        @javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:un:unece:uncefact:data:standard:SPSCertificate:8", prefix = "ram"),
        
        })
package org.kephis.cms.xmlschema.SPSCertificate_8p0;

