//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 07:36:19 PM EAT 
//


package org.kephis.cms.xmlschema.SPSCertificate_8p0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}LevelCode"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}TypeCode"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ItemQuantity"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}NominalGrossWeightMeasure"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}PhysicalSPSShippingMarks"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "levelCode",
    "typeCode",
    "itemQuantity",
    "nominalGrossWeightMeasure",
    "physicalSPSShippingMarks"
})
@XmlRootElement(name = "PhysicalSPSPackage")
public class PhysicalSPSPackage {

    @XmlElement(name = "LevelCode", required = true)
    protected BigInteger levelCode;
    @XmlElement(name = "TypeCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String typeCode;
    @XmlElement(name = "ItemQuantity", required = true)
    protected ItemQuantity itemQuantity;
    @XmlElement(name = "NominalGrossWeightMeasure", required = true)
    protected NominalGrossWeightMeasure nominalGrossWeightMeasure;
    @XmlElement(name = "PhysicalSPSShippingMarks", required = true)
    protected PhysicalSPSShippingMarks physicalSPSShippingMarks;

    /**
     * Gets the value of the levelCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLevelCode() {
        return levelCode;
    }

    /**
     * Sets the value of the levelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLevelCode(BigInteger value) {
        this.levelCode = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the itemQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link ItemQuantity }
     *     
     */
    public ItemQuantity getItemQuantity() {
        return itemQuantity;
    }

    /**
     * Sets the value of the itemQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemQuantity }
     *     
     */
    public void setItemQuantity(ItemQuantity value) {
        this.itemQuantity = value;
    }

    /**
     * Gets the value of the nominalGrossWeightMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link NominalGrossWeightMeasure }
     *     
     */
    public NominalGrossWeightMeasure getNominalGrossWeightMeasure() {
        return nominalGrossWeightMeasure;
    }

    /**
     * Sets the value of the nominalGrossWeightMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link NominalGrossWeightMeasure }
     *     
     */
    public void setNominalGrossWeightMeasure(NominalGrossWeightMeasure value) {
        this.nominalGrossWeightMeasure = value;
    }

    /**
     * Gets the value of the physicalSPSShippingMarks property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalSPSShippingMarks }
     *     
     */
    public PhysicalSPSShippingMarks getPhysicalSPSShippingMarks() {
        return physicalSPSShippingMarks;
    }

    /**
     * Sets the value of the physicalSPSShippingMarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalSPSShippingMarks }
     *     
     */
    public void setPhysicalSPSShippingMarks(PhysicalSPSShippingMarks value) {
        this.physicalSPSShippingMarks = value;
    }

}
