//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 07:36:19 PM EAT 
//


package org.kephis.cms.xmlschema.SPSCertificate_8p0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}PostcodeCode"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}LineOne"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}LineTwo"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}LineThree"/>
 *           &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}LineFour"/>
 *           &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}LineFive"/>
 *         &lt;/sequence>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}CityName"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}CountryID"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}CountryName"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}CityID"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "postcodeCode",
    "lineOne",
    "lineTwo",
    "lineThree",
    "lineFour",
    "lineFive",
    "cityName",
    "countryID",
    "countryName",
    "cityID"
})
@XmlRootElement(name = "SpecifiedSPSAddress")
public class SpecifiedSPSAddress {

    @XmlElement(name = "PostcodeCode", required = true)
    protected String postcodeCode;
    @XmlElement(name = "LineOne", required = true)
    protected String lineOne;
    @XmlElement(name = "LineTwo", required = true)
    protected String lineTwo;
    @XmlElement(name = "LineThree")
    protected String lineThree;
    @XmlElement(name = "LineFour")
    protected LineFour lineFour;
    @XmlElement(name = "LineFive")
    protected LineFive lineFive;
    @XmlElement(name = "CityName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String cityName;
    @XmlElement(name = "CountryID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String countryID;
    @XmlElement(name = "CountryName", required = true)
    protected String countryName;
    @XmlElement(name = "CityID", required = true)
    protected String cityID;

    /**
     * Gets the value of the postcodeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostcodeCode() {
        return postcodeCode;
    }

    /**
     * Sets the value of the postcodeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostcodeCode(String value) {
        this.postcodeCode = value;
    }

    /**
     * Gets the value of the lineOne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineOne() {
        return lineOne;
    }

    /**
     * Sets the value of the lineOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineOne(String value) {
        this.lineOne = value;
    }

    /**
     * Gets the value of the lineTwo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineTwo() {
        return lineTwo;
    }

    /**
     * Sets the value of the lineTwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineTwo(String value) {
        this.lineTwo = value;
    }

    /**
     * Gets the value of the lineThree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineThree() {
        return lineThree;
    }

    /**
     * Sets the value of the lineThree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineThree(String value) {
        this.lineThree = value;
    }

    /**
     * Gets the value of the lineFour property.
     * 
     * @return
     *     possible object is
     *     {@link LineFour }
     *     
     */
    public LineFour getLineFour() {
        return lineFour;
    }

    /**
     * Sets the value of the lineFour property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineFour }
     *     
     */
    public void setLineFour(LineFour value) {
        this.lineFour = value;
    }

    /**
     * Gets the value of the lineFive property.
     * 
     * @return
     *     possible object is
     *     {@link LineFive }
     *     
     */
    public LineFive getLineFive() {
        return lineFive;
    }

    /**
     * Sets the value of the lineFive property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineFive }
     *     
     */
    public void setLineFive(LineFive value) {
        this.lineFive = value;
    }

    /**
     * Gets the value of the cityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityName(String value) {
        this.cityName = value;
    }

    /**
     * Gets the value of the countryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryID() {
        return countryID;
    }

    /**
     * Sets the value of the countryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryID(String value) {
        this.countryID = value;
    }

    /**
     * Gets the value of the countryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

    /**
     * Gets the value of the cityID property.
     * 
     * @return
     *     possible object is
     *     {@link CityID }
     *     
     */
    public String getCityID() {
        return cityID;
    }

    /**
     * Sets the value of the cityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CityID }
     *     
     */
    public void setCityID(String value) {
        this.cityID = value;
    }

}
