//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 07:36:19 PM EAT 
//


package org.kephis.cms.xmlschema.SPSCertificate_8p0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}SPSExchangedDocument"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}SPSConsignment"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "spsExchangedDocument",
    "spsConsignment"
})

@XmlRootElement(name = "SPSCertificate", namespace = "urn:un:unece:uncefact:data:standard:SPSCertificate:8")
public class SPSCertificate {

    @XmlElement(name = "SPSExchangedDocument", namespace = "urn:un:unece:uncefact:data:standard:SPSCertificate:8", required = true)
    protected SPSExchangedDocument spsExchangedDocument;
    @XmlElement(name = "SPSConsignment", namespace = "urn:un:unece:uncefact:data:standard:SPSCertificate:8", required = true)
    protected SPSConsignment spsConsignment;

    /**
     * Gets the value of the spsExchangedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link SPSExchangedDocument }
     *     
     */
    public SPSExchangedDocument getSPSExchangedDocument() {
        return spsExchangedDocument;
    }

    /**
     * Sets the value of the spsExchangedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPSExchangedDocument }
     *     
     */
    public void setSPSExchangedDocument(SPSExchangedDocument value) {
        this.spsExchangedDocument = value;
    }

    /**
     * Gets the value of the spsConsignment property.
     * 
     * @return
     *     possible object is
     *     {@link SPSConsignment }
     *     
     */
    public SPSConsignment getSPSConsignment() {
        return spsConsignment;
    }

    /**
     * Sets the value of the spsConsignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPSConsignment }
     *     
     */
    public void setSPSConsignment(SPSConsignment value) {
        this.spsConsignment = value;
    }

}
