//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 07:36:19 PM EAT 
//
package org.kephis.cms.xmlschema.SPSCertificate_8p0;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ConsignorSPSParty"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ConsigneeSPSParty"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ExportSPSCountry"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ImportSPSCountry"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}UnloadingBaseportSPSLocation"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}ExaminationSPSEvent"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}MainCarriageSPSTransportMovement"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12}IncludedSPSConsignmentItem"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "consignorSPSParty",
    "consigneeSPSParty",
    "exportSPSCountry",
    "importSPSCountry",
    "unloadingBaseportSPSLocation",
    "examinationSPSEvent",
    "mainCarriageSPSTransportMovement",
   // "includedSPSConsignmentItem",
    "IncludedSPSConsignmentItem"
})
@XmlRootElement(name = "SPSConsignment", namespace = "urn:un:unece:uncefact:data:standard:SPSCertificate:8")
public class SPSConsignment {

    @XmlElement(name = "ConsignorSPSParty", required = true)
    protected ConsignorSPSParty consignorSPSParty;
    @XmlElement(name = "ConsigneeSPSParty", required = true)
    protected ConsigneeSPSParty consigneeSPSParty;
    @XmlElement(name = "ExportSPSCountry", required = true)
    protected ExportSPSCountry exportSPSCountry;
    @XmlElement(name = "ImportSPSCountry", required = true)
    protected ImportSPSCountry importSPSCountry;
    @XmlElement(name = "UnloadingBaseportSPSLocation", required = true)
    protected UnloadingBaseportSPSLocation unloadingBaseportSPSLocation;
    @XmlElement(name = "ExaminationSPSEvent", required = true)
    protected ExaminationSPSEvent examinationSPSEvent;
    @XmlElement(name = "MainCarriageSPSTransportMovement", required = true)
    protected MainCarriageSPSTransportMovement mainCarriageSPSTransportMovement;
    @XmlElement(name = "IncludedSPSConsignmentItem", required = true)
    //  protected IncludedSPSConsignmentItem includedSPSConsignmentItem; 
    protected List<IncludedSPSConsignmentItem> IncludedSPSConsignmentItem = new ArrayList<IncludedSPSConsignmentItem>();

    /**
     * Gets the value of the consignorSPSParty property.
     *
     * @return possible object is {@link ConsignorSPSParty }
     *
     */
    public ConsignorSPSParty getConsignorSPSParty() {
        return consignorSPSParty;
    }

    /**
     * Sets the value of the consignorSPSParty property.
     *
     * @param value allowed object is {@link ConsignorSPSParty }
     *
     */
    public void setConsignorSPSParty(ConsignorSPSParty value) {
        this.consignorSPSParty = value;
    }

    /**
     * Gets the value of the consigneeSPSParty property.
     *
     * @return possible object is {@link ConsigneeSPSParty }
     *
     */
    public ConsigneeSPSParty getConsigneeSPSParty() {
        return consigneeSPSParty;
    }

    /**
     * Sets the value of the consigneeSPSParty property.
     *
     * @param value allowed object is {@link ConsigneeSPSParty }
     *
     */
    public void setConsigneeSPSParty(ConsigneeSPSParty value) {
        this.consigneeSPSParty = value;
    }

    /**
     * Gets the value of the exportSPSCountry property.
     *
     * @return possible object is {@link ExportSPSCountry }
     *
     */
    public ExportSPSCountry getExportSPSCountry() {
        return exportSPSCountry;
    }

    /**
     * Sets the value of the exportSPSCountry property.
     *
     * @param value allowed object is {@link ExportSPSCountry }
     *
     */
    public void setExportSPSCountry(ExportSPSCountry value) {
        this.exportSPSCountry = value;
    }

    /**
     * Gets the value of the importSPSCountry property.
     *
     * @return possible object is {@link ImportSPSCountry }
     *
     */
    public ImportSPSCountry getImportSPSCountry() {
        return importSPSCountry;
    }

    /**
     * Sets the value of the importSPSCountry property.
     *
     * @param value allowed object is {@link ImportSPSCountry }
     *
     */
    public void setImportSPSCountry(ImportSPSCountry value) {
        this.importSPSCountry = value;
    }

    /**
     * Gets the value of the unloadingBaseportSPSLocation property.
     *
     * @return possible object is {@link UnloadingBaseportSPSLocation }
     *
     */
    public UnloadingBaseportSPSLocation getUnloadingBaseportSPSLocation() {
        return unloadingBaseportSPSLocation;
    }

    /**
     * Sets the value of the unloadingBaseportSPSLocation property.
     *
     * @param value allowed object is {@link UnloadingBaseportSPSLocation }
     *
     */
    public void setUnloadingBaseportSPSLocation(UnloadingBaseportSPSLocation value) {
        this.unloadingBaseportSPSLocation = value;
    }

    /**
     * Gets the value of the examinationSPSEvent property.
     *
     * @return possible object is {@link ExaminationSPSEvent }
     *
     */
    public ExaminationSPSEvent getExaminationSPSEvent() {
        return examinationSPSEvent;
    }

    /**
     * Sets the value of the examinationSPSEvent property.
     *
     * @param value allowed object is {@link ExaminationSPSEvent }
     *
     */
    public void setExaminationSPSEvent(ExaminationSPSEvent value) {
        this.examinationSPSEvent = value;
    }

    /**
     * Gets the value of the mainCarriageSPSTransportMovement property.
     *
     * @return possible object is {@link MainCarriageSPSTransportMovement }
     *
     */
    public MainCarriageSPSTransportMovement getMainCarriageSPSTransportMovement() {
        return mainCarriageSPSTransportMovement;
    }

    /**
     * Sets the value of the mainCarriageSPSTransportMovement property.
     *
     * @param value allowed object is {@link MainCarriageSPSTransportMovement }
     *
     */
    public void setMainCarriageSPSTransportMovement(MainCarriageSPSTransportMovement value) {
        this.mainCarriageSPSTransportMovement = value;
    }

    /**
     * Gets the value of the includedSPSConsignmentItem property.
     *
     * @return possible object is {@link IncludedSPSConsignmentItem }
     *
     */
    public List<IncludedSPSConsignmentItem> getIncludedSPSConsignmentItem() {
        return IncludedSPSConsignmentItem;
    }

    /**
     * Sets the value of the includedSPSConsignmentItem property.
     *
     * @param value allowed object is {@link IncludedSPSConsignmentItem }
     *
     *
      public void setIncludedSPSConsignmentItem(IncludedSPSConsignmentItem
      value) { this.includedSPSConsignmentItem = value; }
    .*/
    public void setIncludedSPSConsignmentItem(List<IncludedSPSConsignmentItem> includedSPSConsignmentItemList) {
     
 
        IncludedSPSConsignmentItem =includedSPSConsignmentItemList;  
    }
  public void setIncludedSPSConsignmentItem(IncludedSPSConsignmentItem includedSPSConsignmentItem) {
     
 
        IncludedSPSConsignmentItem.add(includedSPSConsignmentItem);  
    }
}
