//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 07:36:19 PM EAT 
//


package org.kephis.cms.xmlschema.SPSCertificate_8p0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}ID"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}Description"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}TypeCode"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}StatusCode"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}IssueDateTime"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}IssuerSPSParty"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}RecipientSPSParty"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}IncludedSPSNote"/>
 *         &lt;element ref="{urn:un:unece:uncefact:data:standard:SPSCertificate:8}SignatorySPSAuthentication"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "id",
    "description",
    "typeCode",
    "statusCode",
    "issueDateTime",
    "issuerSPSParty",
    "recipientSPSParty",
    "includedSPSNote",
    "signatorySPSAuthentication"
})
@XmlRootElement(name = "SPSExchangedDocument", namespace = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12")
public class SPSExchangedDocument {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "TypeCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String typeCode;
    @XmlElement(name = "StatusCode", required = true)
    protected BigInteger statusCode;
    @XmlElement(name = "IssueDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar issueDateTime;
    @XmlElement(name = "IssuerSPSParty", required = true)
    protected IssuerSPSParty issuerSPSParty;
    @XmlElement(name = "RecipientSPSParty", required = true)
    protected RecipientSPSParty recipientSPSParty;
    @XmlElement(name = "IncludedSPSNote", required = true)
    protected IncludedSPSNote includedSPSNote;
    @XmlElement(name = "SignatorySPSAuthentication", required = true)
    protected SignatorySPSAuthentication signatorySPSAuthentication;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatusCode(BigInteger value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the issueDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDateTime() {
        return issueDateTime;
    }

    /**
     * Sets the value of the issueDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDateTime(XMLGregorianCalendar value) {
        this.issueDateTime = value;
    }

    /**
     * Gets the value of the issuerSPSParty property.
     * 
     * @return
     *     possible object is
     *     {@link IssuerSPSParty }
     *     
     */
    public IssuerSPSParty getIssuerSPSParty() {
        return issuerSPSParty;
    }

    /**
     * Sets the value of the issuerSPSParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuerSPSParty }
     *     
     */
    public void setIssuerSPSParty(IssuerSPSParty value) {
        this.issuerSPSParty = value;
    }

    /**
     * Gets the value of the recipientSPSParty property.
     * 
     * @return
     *     possible object is
     *     {@link RecipientSPSParty }
     *     
     */
    public RecipientSPSParty getRecipientSPSParty() {
        return recipientSPSParty;
    }

    /**
     * Sets the value of the recipientSPSParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipientSPSParty }
     *     
     */
    public void setRecipientSPSParty(RecipientSPSParty value) {
        this.recipientSPSParty = value;
    }

    /**
     * Gets the value of the includedSPSNote property.
     * 
     * @return
     *     possible object is
     *     {@link IncludedSPSNote }
     *     
     */
    public IncludedSPSNote getIncludedSPSNote() {
        return includedSPSNote;
    }

    /**
     * Sets the value of the includedSPSNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludedSPSNote }
     *     
     */
    public void setIncludedSPSNote(IncludedSPSNote value) {
        this.includedSPSNote = value;
    }

    /**
     * Gets the value of the signatorySPSAuthentication property.
     * 
     * @return
     *     possible object is
     *     {@link SignatorySPSAuthentication }
     *     
     */
    public SignatorySPSAuthentication getSignatorySPSAuthentication() {
        return signatorySPSAuthentication;
    }

    /**
     * Sets the value of the signatorySPSAuthentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatorySPSAuthentication }
     *     
     */
    public void setSignatorySPSAuthentication(SignatorySPSAuthentication value) {
        this.signatorySPSAuthentication = value;
    }

}
